---
ansible_user: ubuntu
ip_address: 5.6.7.8
ssh_pem: /Users/jjklug/.ssh/aws-test-key.pem
base_utilities:
  - git
  - curl
  - wget
  - unzip
  - tar
  - vim
  - htop
  - firewalld
  - python3
  - python3-pip
  - binutils
  - net-tools
